//screens will be stored in an array of objects.
//each screen has an id, main text and a button panel

var fieriScreens = [
    {
        "screenID":0,
        "imageName":"images/start.jpg",
        "musicName":"music/MainTitle.mp3",
        "mainText":"A stout, well-tanned man in a flame-blazen shirt and bleached tips approaches you.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"You recognize him, that's GUY FIERI! You love his show!",
                "buttonGoTo":1
            },
            {
                "buttonPos":1,
                "buttonText":"Leave",
                "buttonGoTo":2
            },
            {
                "buttonPos":2,
                "buttonText":"You've seen the memes, that's the dude that loves burgers",
                "buttonGoTo":28
            },
            {
                "buttonPos":3,
                "buttonText":"Eat one of your limbs out of panicked depseration",
                "buttonGoTo":0,
                "addOnText":"You have a hard time picking which limb to eat but settle on your left hand. You now have no left hand."
            }
        ]
    },
    {
        "screenID":1,
        "imageName":"images/smile.jpg",
        "mainText":"You are visibly nervous. A massive smile appears on his face. 'Ah, a true fan' he says as he notices the sparkles in your eyes.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Profess your leigitmate love for his culinary prowess",
                "buttonGoTo":3

            },
            {
                "buttonPos":1,
                "buttonText":"Play it coy and tell him you have no idea who he is",
                "buttonGoTo":21
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":2,
        "mainText":"You turn around and walk away from the stout man. Nothing happened.",
        "imageName":"images/nothing.jpg",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":0

            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":0
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":0
            }
        ]
    },
    {
        "screenID":3,
        "mainText":"You tell him you really enjoy the energy he brings to his content, and that you feel his taste in food and his desire to share his passion with others has marked you positively. He smiles, but remains silent. His orange-tinted cheeks begin to take on a rosy material.",
        "imageName":"images/enamored.jpg",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Ask him what he's doing in your university's parking garage",
                "buttonGoTo":4
            },
            {
                "buttonPos":1,
                "buttonText":"Remain silent",
                "buttonGoTo":30

            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":0
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":0
            }
        ]
    },
    {
        "screenID":4,
        "imageName":"images/dream.jpg",
        "mainText":"You ask him what he's doing in your school's parking garage, which is currently empty. He tells you that you should know, since it's your dream.",
        "musicName":"music/dream.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"What does he mean, 'it's MY dream'?",
                "buttonGoTo":5

            },
            {
                "buttonPos":1,
                "buttonText":"Realize you are now lucid dreaming",
                "buttonGoTo":6
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":5,
        "imageName":"images/flavortownDeath.jpg",
        "musicName":"music/gameover.mp3",
        "mainText":"You're dumbfounded. You ask him what he means by 'it's MY dream'. He smirks. 'Welcome to Flavortown, baby' he whispers as he raises his arms. Welcome to Flavortown.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0

            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":6,
        "imageName":"images/lucidDream.jpg",
        "mainText":"You realize now that you are lucid dreaming. You are able to pause your dream, resume it, quit, change settings... pretty much anything. However, in the moment, only two options come to mind.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Kiss Guy Fieri",
                "buttonGoTo":7
            },
            {
                "buttonPos":1,
                "buttonText":"Kill Guy Fieri",
                "buttonGoTo":15
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":7,
        "imageName":"images/kiss.jpg",
        "mainText":"You gently carress Guy's shoulders. They're firm, but soft, like his lips. You let out a slight sigh; you've finally found the person you're meant to be with. Your connection is unspeakable, something words were never construed to describe. You want this feeling to last forever. You gaze into his eyes, and lean in for a kiss. You feel a burning sensation on your lips. Guy Fieri has turned into his evil form, Guy Fiery. He's a literal burning mass of flesh. You retreat, but still see his soft eyes through the flames.",
        "musicName":"music/kiss.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Reach for him one last time to pull him out of the fire",
                "buttonGoTo":8
            },
            {
                "buttonPos":1,
                "buttonText":"Abandon the dream, and him",
                "buttonGoTo":12
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":8,
        "imageName":"images/flamingGuy.jpg",
        "mainText":"You reach into the flames, feeling the heat on your skin, smelling the hair on your arm burning. It smells good somehow. It's satisfying to know you're so committed to something that it's changing you, physically. However, you reach in and nothing's there. It hurts to keep your arm in the fire but you keep it there, hoping to find Guy eventually. You wave your arm around, but no one's there.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Keep your arm in the fire",
                "buttonGoTo":9
            },
            {
                "buttonPos":1,
                "buttonText":"Abandon the dream, and him",
                "buttonGoTo":12
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":9,
        "imageName":"images/flamingGuy2.jpg",
        "mainText":"You keep your arm in the fire, devoted to searching for Guy within the flaming mess. You no longer feel pain. You can no longer see your arm, either. You're not sure if your arm is gone, or if it's covered by the flames. You're too scared to pull it out and see.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Keep your arm in the fire, forever",
                "buttonGoTo":11
            },
            {
                "buttonPos":1,
                "buttonText":"Pull out your arm",
                "buttonGoTo":10
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":10,
        "imageName":"images/armWin.jpg",
        "mainText":"You pull your arm out of the fire. It's gone. And so is Guy. The fire subsides, and you are left alone. Although you're sad about losing your arm, and Guy, you can seek comfort in knowing that you're still in control of yourself and your decisions. You leave the area, never to return.",
        "musicName":"music/win.mp3",
        "buttonPanel":[
            {
                "buttonPos":1,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":11,
        "imageName":"images/stayLoss.jpg",
        "mainText":"Crippling indecision overcomes you. You don't want to abandon Guy by removing your arm, but as such you will never know if you arm is still there or not. You stand, waiting. Forever. You can't realize he's gone, and you're so used to the pain that its become all that you know.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":12,
        "imageName":"images/abandon.jpg",
        "mainText":"You decide to abandon the dream. He's gone. He isn't who you thought he was. Quit while you're ahead, before you get hurt. To leave your dream, you must die.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Die",
                "buttonGoTo":13
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":13,
        "imageName":"images/knife.jpg",
        "mainText":"You conjure up a knife, then wonder if it's the best way to go out. You've never thought of this before, surprisingly. You hate the idea, you hate its implications, but there's no other way out. You drop the knife and it disappears. You need to find another way to die.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Love Guy Fieri unconditionally",
                "buttonGoTo":14
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":14,
        "imageName":"images/unconditional.jpg",
        "mainText":"You let your emotions take over, your gut drives you. You give in to your feelings towards Guy. Even a flaming, harmful mess you still desire to be with him. You abandon everything to be with him. As such, you leave yourself completely open. You open your arms, welcoming a final carress from Guy. Guy lunges from within the fire and slits your throat.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":15,
        "imageName":"images/kill.jpg",
        "mainText":"You feel the urge to kill Guy Fieri. You conjure a spatula. A bucket of flaming hot coals appears by your side. You let out in a primal scream: 'WELCOME TO FLAVORTOWN' as you pick up a hot coal, throw it into the air, then hit it with your spatula. You miss Guy by a mile. He's now aware of your intentions to harm him and has turned around. He's apparently building something.",
        "musicName":"music/kill.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Wait to see what he's got cookin",
                "buttonGoTo":16
            },
            {
                "buttonPos":1,
                "buttonText":"Take this opportunity to kill him",
                "buttonGoTo":18
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":16,
        "imageName":"images/cake.jpg",
        "mainText":"You wait. Guy turns around. He's baked you a cake with decorative frosting flames. There's text on the cake. It reads: 'I care about you. I am in love with every facet of you, purely because it is you. Your features may change, physically and emotionally, but as long as you're you I will be by yourside through those changes.'",
        "musicName":"music/cake.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Kiss Guy Fieri",
                "buttonGoTo":7
            },
            {
                "buttonPos":1,
                "buttonText":"Slap the cake out of his hands",
                "buttonGoTo":17
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":17,
        "imageName":"images/slapCake.jpg",
        "mainText":"You hate what he wrote. You slap the cake out of his hands. His eyes begin to water and leak. 'I made that for you' he whimpers. You can't stand how much weakness he is showing. You pick up a flaming hot coal. He watches you, fearful and hurt, as you lob it into the air. When it comes back down you hit it with your spatula, sending the flaming hot coal bullet squarely on Guy's chest. It goes through his chest, through his heart, and becomes lodged in there. He looks at you, tears in his eyes. 'No one has ever hurt me as much as you've hurt me.' He falls over, dead. You killed Guy Fieri.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":18,
        "imageName":"images/killGuy.jpg",
        "mainText":"You decide to take this opportunity to kill him. You grab another coal, this time you won't miss. You lob it into the air. As you do, Guy turns around. He's baked you a cake with decorative frosting flames. You hit the coal with the spatula as it decents. There's text on the cake. It reads: 'I care about you. I am in love with every facet of you, purely because it is you. Your features may change, physically and emotionally, but as long as you're you I will be by your side through those changes.' You somehow read all of this before the flaming hot coal bullet lands squarely on Guy's chest. It goes through his chest, through his heart, and becomes lodged in there. He looks up, tears in his eyes. 'No one has ever hurt me as much as you've hurt me.' He falls over, dead. You killed Guy Fieri.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":19,
        "imageName":"images/choices.jpg",
        "mainText":"You shout out the first thing that comes to your mind. 'I FIGHT DEMONS BECAUSE A BABY IN HEAVEN TELLS ME TO' is what ends up coming out of your mouth at an incredibly loud volume. Guy flinches as you scream. His face, now scrunched in disgust, slowly regains its form. A small smile appears on his face. 'I think I love you', he says in an incredibly low, timid voice. 'Finally, someone who understands me.'",
        "musicName":"music/choices.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Kiss Guy Fieri",
                "buttonGoTo":7
            },
            {
                "buttonPos":1,
                "buttonText":"Kill Guy Fieri",
                "buttonGoTo":15
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":20,
        "imageName":"images/headExplode.jpg",
        "mainText":"You remain silent despite the incredible discomfort. Your head begins to swell. Guy is visibly shaken, with an intense look of fear on his face. You feel your pores open up, blood pouring out of each one. Your eyes slink out of their sockets, your nostrils tear at the seams and your lips tear as they are stretched. You're dying. Your head explodes. You're dead. Next time, say something.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":21,
        "imageName":"images/cryingGuy.jpg",
        "mainText":"You try to come off cool and composed by telling him you're not sure who he is. He's visibly saddened by this comment. A single tear begins to roll down his left cheek.",
        "musicName":"music/sadGuy.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Tell him to stop crying",
                "buttonGoTo":22
            },
            {
                "buttonPos":1,
                "buttonText":"Ask him what's wrong",
                "buttonGoTo":23
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":22,
        "imageName":"images/frustratedGuy.jpg",
        "mainText":"You tell him to stop crying. You begin to sing All Star by Smash Mouth. Guy Fieri cries harder. Through the sobs you hear 'I'm so tired of this!'",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Ask him what he's tired of",
                "buttonGoTo":23
            },
            {
                "buttonPos":1,
                "buttonText":"-- THE WORLD WAS GONNA ROLL ME I AIN'T THE SHARPEST...",
                "buttonGoTo":24
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":23,
        "imageName":"images/guyYell.jpg",
        "mainText":"Guy Fieri yells in frustration. 'I'm tired of being thought of as a joke!' He clenches his teeth and bears them, eyes watering up, his fists balled up and shaking.",
        "musicName":"music/angryGuy.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Tell him to calm down, it's not a big deal",
                "buttonGoTo":24
            },
            {
                "buttonPos":1,
                "buttonText":"Apologize",
                "buttonGoTo":27
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":24,
        "imageName":"images/glowingGuy.jpg",
        "mainText":"Guy Fieri begins to glow red. The light around you two has become dim. You feel a rumbling at your feet.",
        "musicName":"music/incomingFight.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Do nothing",
                "buttonGoTo":25
            },
            {
                "buttonPos":1,
                "buttonText":"Attack Guy Fieri",
                "buttonGoTo":26
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":25,
        "imageName":"images/guyMayo.jpg",
        "mainText":"You do nothing. Guy Fieri raises both arms, palms facing towards you. Sudden, intense jets of mayonnaise burst out of his palms and into your eyes. You've been blinded. Guy then yells into your ears so hard that you pass out. Game over.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":26,
        "imageName":"images/swatted.jpg",
        "mainText":"You run towards Guy, fists clenched and ready to attack. He swats you away with strength so extraordinary that your body disintegrates due to the sheer force of his swat. You've passed away.",
        "musicName":"music/gameover.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Restart",
                "buttonGoTo":0
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":27,
        "imageName":"images/apology.jpg",
        "mainText":"You apologize and Guy calms down.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Ask him what he's doing in your university's parking garage",
                "buttonGoTo":4
            },
            {
                "buttonPos":1,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":28,
        "imageName":"images/videocd.jpg",
        "mainText":"You begin to laugh. You pull out a copy of Shrek on VideoCD and point to it. You tell him he looks just like the guy who sings the song at the beginning of the film. A single tear rolls down his left cheek as you finish your sentence.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Ask him what's wrong",
                "buttonGoTo":23
            },
            {
                "buttonPos":1,
                "buttonText":"Begin to cry as well",
                "buttonGoTo":29
            },
            {
                "buttonPos":2,
                "buttonText":"Tell him to stop crying",
                "buttonGoTo":22
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":29,
        "imageName":"images/bothCry.jpg",
        "mainText":"You begin to cry. The man begins to cry harder. Through the sobs he utters 'My name... is Guy... sniff... Fieri...'",
        "musicName":"music/bothCry.mp3",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Remain silent",
                "buttonGoTo":30
            },
            {
                "buttonPos":1,
                "buttonText":"Play it coy and tell him you have no idea who he is",
                "buttonGoTo":21
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
    {
        "screenID":30,
        "imageName":"images/silence.jpg",
        "mainText":"You remain silent. The tension grows, the air is thick, You feel your neck begin to shake as your pulse pounds through your wrists and neck. You need to say something quick or you feel like your head will explode.",
        "buttonPanel":[
            {
                "buttonPos":0,
                "buttonText":"Shout out the first thing that comes to mind",
                "buttonGoTo":19
            },
            {
                "buttonPos":1,
                "buttonText":"Remain silent despite the discomfort",
                "buttonGoTo":20
            },
            {
                "buttonPos":2,
                "buttonText":"",
                "buttonGoTo":100
            },
            {
                "buttonPos":3,
                "buttonText":"",
                "buttonGoTo":100
            }
        ]
    },
];